name: E2E tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ALLURE_RESULTS_PATH: ./allure-results

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.27.1-focal
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.1
          architecture: x64
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest --alluredir=${{ env.ALLURE_RESULTS_PATH }}
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ${{ env.ALLURE_RESULTS_PATH }}
          retention-days: 5
  generate-report:
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: allure-results
          path: ${{ env.ALLURE_RESULTS_PATH }}
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: ${{ env.ALLURE_RESULTS_PATH }}
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
      - name: Deploy to Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: allure-report
  pr-comment:
    needs: generate-report
    if: ${{ github.event.workflow_run.workflows.e2e.event_name }} == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Add link to PR
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            Test report will generated at: ${{ secrets.PAGES_URL }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'